language: ruby
rvm:
- 2.5.0
sudo: false
cache: bundler
before_install:
- chmod +x _scripts/gemfile.sh
- _scripts/gemfile.sh
- npm i -g npm@6.1.0
install:
- npm install
- bundle install
branches:
  only:
  - publish
notifications:
  email:
    recipients:
    - secure: Y6mppPQ+Ia9AO1oTdxy4Umh+yh95j81VB4Vd05KMHwvwocDgd7khY9EmSPjb+rxXUE+19TQOizqJ3LkIlw3zyFMd82AcdABYNvKmrwvbtVOFm44Az7KF3eOYgvfyMBjATCRDR5/sW/neOJEOksi/gyeUTxTIWh+wr25DWceBy7Kf0TvR4e95bnDnNaOt/qDUkq+074yUkxNjFxiIpS3D3rJM4UuI23rpFbPszp09gd5cwRZwIzN1FIQY8pgQe6QciCcvb6Q4+T48Utt4JFnRXn2SxQ7T3U8wAvQq21xrQw+BTVoBvN1ZdzXbsti4ZrpBpfsU2IGzfNFnsRYK/MIMbpWMsN5iPDPLqnvfp6XNFJHazFv9wQ4vUpatyyTv4Jp8DXu5M8CGct0AVBP9DfOScnILSJuRdVfofsYVDNCiHL6az5E6h8sDOZead9ThI4qeFSsl0BZZzi7yVwaPfPttZRVHERsYwB4Elh/VDgTF7jisyuHjP0BxA5zrkaTiRf1knkdPlul2HvafaWIRYjwyPz5gNr+bgJxrEsWO2/P4VWcKy3k/exjIZf5WH0zeWgUUrn/8cPj1zSRbLenWsd9Q50T3Fd9hnx8beHx6G4VTYTUBig20MqN5IZj4ygJeMx0b8RL/NYDOsU1KcbNbTmpm2PVaIb0W0ETp1mwKkEJ7qZs=
    - secure: DLwExuGUST+J1yuA783kP9xibtUy7QISkxTJk3ZLkBx8WT5xT2TasO6dJrXdTyJMEYygJGQXUSGXel2IQ+ArGdpN9SCBuEJRtZjtytHKmJd7GhrbaGLQP0NT3wAbnkXl/8zp3dVgsKYh4LkUjy2RfG1St9imElwYRBmUcdOCk1aBOnwqAta8koVcA5bDPkP6/6giQSDgNDRiPD71LNufwGyhuEH9TrX8n6mS59anCIgsGyVM3VOK0CNF+0uB6+ItqGe+JU9d0VchD4PldRQ5iMejluIBaBzp5UlPwaLTSGNx8AcI4LIbvBqs6GrCQQ3GS8kEROeC6gdKDCvoJJaiFLQMmlKaJeBmOiI4JbgACQYGOxD255NlJQSWTQhgfJi8CeopvHH27Rt56LKZX+5eQ5XnMH21UM8WUHbSrxMVH6IqI8OZZoofBCH9mAlAlMKKByacrrJuBRvhofPwXBr5cK7FoIJSozhN6KwGbZP9GrMfy3mxt/4elhaooavfK/scHY7PVoPl0Yzf0FzeqIRpO53L4WUoPpAdBjmqfqMFnwVjv9AAA5fV91qTA9e9DNeRHhnBoQbRYcwZjYGFgqoFc0ZHAtvvz1G0nMdF+2HC1M3gu8C2EioMH4/cqkJZm4INA1iRLk9/1J89KuBvv1xPYYXem3iAbBRxGGi7W4w5zh0=
    on_success: always
    on_failure: always
before_script:
- npm install -g gulp-cli
script:
- chmod +x _scripts/build.sh
- _scripts/build.sh
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
after_failure:
- chmod +x _scripts/gemfile.sh
- _scripts/gemfile.sh
- npm i -g npm@6.1.0
- npm install
- bundle install
- chmod +x _scripts/build.sh
- _scripts/build.sh
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
env:
  global:
  - secure: NUZc5Q35Kkyc2nbpx6yCMwkMZS221bug2I7zm5Wx2lCx0r26n2poboEZuMDFrhLSGlfzEKHq95y1RRYeqA/djZEhjytIyXsl6Xq8GAQ9xYLCfSp0DPSecbbTm1tru8dw+ihYjcATdkOxvTkQy0/BPZ7fvRqCz0Ns+RWRUlau8lCRX31G7h9BNIlQEH3Y7nKIqiXk5OylQUYOvfO4aYjDF8JUqXTfuMmbytN6AEUQf53l8pgWvyvRBkV6OCuBZEwENRcfsXvKR+7PeHK6HkeJyT9EqVGg+ndBhPquKQH0Xu58rsqi0kr8ga2CmDce0o1OwpASRyuW2vjtwcSseVq63Uir2NMXgjuzZwnoNSuLjjKYMiCILtZnDmh/NU2D+UypH7xtxnhC0VrFV24Ii2cx2z0QHHFC+V3o5LtZhOxTXI4CdzeoNj9MD4Zf1N42wdOvKDDUBkLUdvGsd4Vz3zJm631ZxwwTMZFzJ9TCeiJOAha6q7cmC4F2qAFjVyaTbf6lRr2xKBuCVQTErVxPFIQwZXurHNgNzKDDexuvo7Yk+Gtb8LnHxVLRo5dA/yTT/9RvbCTjdS9Efl9e2m5moYLUalkRbng1VjLctsCZfF+IB1tGPJxaJ+22bpilTB8VHIW+NdJZ7LnEpQjZUKCVZ5yWIK05Njv6td7LHQdEMZqQW/0=
  - secure: LYsNHM3h090wqIgEVGNWl0EKwO4Gq7F935WDFFWL7cTSbZFiQQfRY5qKeLeTlt4QUy+VNPzuw1wosNQScAM+2prr3O61tFsobijy/EUCzoBYa6NVgypezqGk7smWgrr/2g8x18Ot+RASQgltKdfkUUcDMrHTIyademZWD15hSoTaIy6wLkzO3gdYqlAoI2nIc5JghSAlBz8/Pzd56/IfdPViWApjE9DTZoLC1Ttty1j24dpu8Hxsmdz9RsRxBmyGEB0orMQbdy/RxnshlT0+/FN7NyxD2Z/xwahQ+UYZy7zd9pMquyYONDOQv31AaHhGnfnue+tim2lyerNJu8VYPvCL8i8wCTwScnj7wQQDMiqFKVtk1aTCA+WSkdMe1GS4aJ0IUS/YEbkkFygTf+xAuqteFgXxSvJzz6FSdccLdy736uLJakAihbG3yGT/1NanjZNjNgJFYIPRX97kWXpdT5/nUsgIGM6e9ElZaJQdW4kI7BqXw3LRu/HEp3z0/yCVXWaD3xuIwRFJjDmU7iaqQg6pmkXhPEnwJJELhTln/YbFmPaSWFLsaR6X8WmNEYcz76H3ptwBd7+7xRw4bZK5kbHuzNKzC3x7WYCHd+G6xVoBSwikPaWPiERJ4ZkyoXzyhUdoC5mt3rvx5OCFhM751K2UK76qDfB2degzpy5HkC4=
