title: "Kankakee Community College"
# Build
site_title: "Adult & Community Education"
site_name: "Adult & Community Education"
theme: 'kcc-gem-theme'
url: https://adulted.kcc.edu
google-tag_key: GTM-M4MDTMS
translate: true ## Uncomment to activate Google Translate Powers (unfortunately no cowpowers)!!
nav_links:
  - link_text: About
    link_href: 'about'
    button: false
  - link_text: Programs
    link_href: 'programs'
    button: false
  - link_text: Resources
    link_href: 'resources'
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
  - link_text: Enroll
    button: true
    dropdown:
      - text: Community Literacy
        href: 'programs/community-literacy'
      - text: English as a Second Language
        href: 'programs/esl'
      - text: GED/High School Equivalency
        href: 'programs/ged'
      - text: 'New! GED+Career'
        href: 'programs/ged/ged-plus-career'
sub-nav_links:
  - link_text: 'GED/HiSet'
    link_href: 'programs/ged'
  - link_text: ESL
    link_href: 'programs/esl'
  - link_text: 'Community Literacy'
    link_href: 'programs/community-literacy'
collections:
  students:
    output: false
  posts:
    output: false
    _hide_content: true
  contacts:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "/assets/adobe/"
  - "gulp-tasks/"
  - "install.sh"
  - "siteicon.png"
  - "webpack.config.js"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"
