collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - tabs
      - students
      - contacts

collections_config:
  pages:
    path: /
    name: Pages
    icon: description
    # This list is your 'Explorer configuration'
    glob:
      - "**/*.html"     # Show all HTML files
      - "**/*.md"       # Show all Markdown files
      - "!pa11y.*"      # HIDE accessibility logs
      - "!_data/**"     # HIDE the data folder
      - "!node_modules" # HIDE dependencies
      - "!*.mjs"        # HIDE your utility scripts
  tabs:
    path: _tabs
    icon: tab
    create:
      path: '[relative_base_path]/{name|slugify}.md'
    add_options:
      - name: New tab
        schema: tab
        icon: add
      - name: New tab with custom ID
        schema: tab_alternate_id
        icon: add
    
    # 2. This defines the templates available to this collection
    schemas:
      tab:
        path: .cloudcannon/schemas/tab.md
      tab_alternate_id:
        path: .cloudcannon/schemas/tab_alternate_id.md
  students:
    path: _students
    name: Student Testimonials
    icon: 3p
    create:
      path: '[relative_base_path]/{name|slugify}.md'
    _inputs:
      date:
        instance_value: NOW
        hidden: true
    add_options:
      - name: New testimonial
        schema: student
        icon: add
    schemas:
      student: .cloudcannon/schemas/student_testimonial.md
  contacts:
    path: _contacts
    icon: person
    create:
      path: '[relative_base_path]/{name|slugify}.md'
    add_options:
      - name: New contact
        schema: contact
        icon: person_add
    schemas:
      contact: 
        path: .cloudcannon/schemas/contact.md
    _inputs:
      name:
        type: text
      contacts_title:
        type: text
        comment: KCC job title
      department_email:
        comment: Optionally display the department email (e.g. adulted@kcc.edu).
      display_order:
        type: number
        comment: Controls the display order of contacts (1 is first).

_inputs:
  baseurl:
    hidden: true
  layout:
    hidden: true
  title:
    hidden: true
  sub-nav_section:
    hidden: true

_comments:
  description: "Descriptions are seen by search engines like Google and displayed in search results"
