collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - tabs
      - students
      - contacts

collections_config:
  pages:
    path: /
    name: Pages
    icon: description
    # This list is your 'Explorer configuration'
    glob:
      - "**/*.html"     # Show all HTML files
      - "**/*.md"       # Show all Markdown files
      - "!pa11y.*"      # HIDE accessibility logs
      - "!_data/**"     # HIDE the data folder
      - "!node_modules" # HIDE dependencies
      - "!*.mjs"        # HIDE your utility scripts
  tabs:
    add_options:
      - name: Add Tab
        icon: tab
        schema: tab
    
    # 2. This defines the templates available to this collection
    schemas:
      tab:
        path: .cloudcannon/schemas/tab.md
        icon: tab

_inputs:
  baseurl:
    hidden: true
  layout:
    hidden: true
  title:
    hidden: true
  sub-nav_section:
    hidden: true

_comments:
  description: "Descriptions are seen by search engines like Google and displayed in search results"
